Failing if the config is new

diff --git a/.azure/templates/update-tag-and-send-pr.yml b/.azure/templates/update-tag-and-send-pr.yml
--- a/.azure/templates/update-tag-and-send-pr.yml
+++ b/.azure/templates/update-tag-and-send-pr.yml
@@ -46,7 +46,15 @@ steps:
       echo "$trimmedUpdatedConfigs" | tr ',' '\n' | while read updatingConfig; do
         IFS='=' read -ra config <<< "$updatingConfig"
         echo "Updating ${config[0]} config to ${config[1]}"
-        sed -i "s#^${config[0]}.*#${config[0]}=${config[1]}#" "$envFileName"
+
+        count=$(grep -c "^${config[0]}=" "$envFileName" || true)
+        if [[ "$count" -gt 0 ]]
+        then
+          sed -i "s#^${config[0]}.*#${config[0]}=${config[1]}#" "$envFileName"
+        else
+          echo "Failing the build because config ${config[0]} is not found in $envFileName"
+          exit 1
+        fi
       done
     fi
 
