[MAIN] add runtime configs

diff --git a/.azure/component-image-tag-update.yml b/.azure/component-image-tag-update.yml
--- a/.azure/component-image-tag-update.yml
+++ b/.azure/component-image-tag-update.yml
@@ -33,6 +33,26 @@ steps:
       $KUSTOMIZE edit set image "$imageName"
     done
 
+    updatedConfigs="${{ parameters.ImageUpdateTrigger.updatedConfigs }}"
+    envFileName='common-env-variables.yaml'
+    if [ ! -z "$updatedConfigs" ]
+    then
+      trimmedUpdatedConfigs=${updatedConfigs//$'\n'/}
+      echo "Configs : $trimmedUpdatedConfigs"
+      echo "$trimmedUpdatedConfigs" | tr ',' '\n' | while read updatingConfig; do
+        IFS='=' read -ra config <<< "$updatingConfig"
+        echo "Updating ${config[0]} config to ${config[1]}"
+        count=$(grep -c "^${config[0]}=" "$envFileName" || true)
+        if [[ "$count" -gt 0 ]]
+        then
+          sed -i "s#^${config[0]}.*#${config[0]}=${config[1]}#" "$envFileName"
+        else
+          echo "Failing the build because config ${config[0]} is not found in $envFileName"
+          exit 1
+        fi
+      done
+    fi
+
     git config --global user.email "choreo-cicd@wso2.com"
     git config --global user.name "Choreo CI Agent"
     git diff
